version: "3.7"

services:
  cf:
    platform: linux/x86_64
    build: ./
    container_name: cf
    restart: always
    ports:
      - "80:80"
      - "8888:8888" # REMOVE IN PROD - THIS IS FOR ADMIN AT http://localhost:8888/lucee/admin/server.cfm
    volumes:
      - ./www:/var/www
  database:
    platform: linux/x86_64
    image: mariadb
    container_name: cf_maria
    restart: always
    ports:
        - "3306:3306"
    environment:
        MARIADB_ROOT_PASSWORD: Yahoo123
        MARIADB_DATABASE: cfdb
        MARIADB_USER: cfdbuser
        MARIADB_PASSWORD: Yahoo123

